// Product photography, hosted on maporoo.com.
// Keyed by SKU; filenames follow the product slug so the paths carry keyword
// weight in Google Images. Files live in public/images/products/.
// Regenerate only if the source imagery changes.

export const productImages: Record<string, string[]> = {
  "M3011": [
    "/images/products/rose-peptide-cream-mask-80ml-1.jpg",
    "/images/products/rose-peptide-cream-mask-80ml-2.jpg",
    "/images/products/rose-peptide-cream-mask-80ml-3.jpg",
    "/images/products/rose-peptide-cream-mask-80ml-4.jpg",
    "/images/products/rose-peptide-cream-mask-80ml-5.jpg",
    "/images/products/rose-peptide-cream-mask-80ml-6.jpg",
    "/images/products/rose-peptide-cream-mask-80ml-7.jpg",
    "/images/products/rose-peptide-cream-mask-80ml-8.jpg",
  ],
  "M3030": [
    "/images/products/scalp-vitality-serum-30ml-1.jpg",
    "/images/products/scalp-vitality-serum-30ml-2.jpg",
    "/images/products/scalp-vitality-serum-30ml-3.jpg",
    "/images/products/scalp-vitality-serum-30ml-4.jpg",
    "/images/products/scalp-vitality-serum-30ml-5.jpg",
    "/images/products/scalp-vitality-serum-30ml-6.jpg",
    "/images/products/scalp-vitality-serum-30ml-7.jpg",
    "/images/products/scalp-vitality-serum-30ml-8.jpg",
  ],
  "M3031": [
    "/images/products/moroccan-hair-oil-100ml-1.jpg",
    "/images/products/moroccan-hair-oil-100ml-2.jpg",
    "/images/products/moroccan-hair-oil-100ml-3.jpg",
    "/images/products/moroccan-hair-oil-100ml-4.jpg",
    "/images/products/moroccan-hair-oil-100ml-5.jpg",
    "/images/products/moroccan-hair-oil-100ml-6.jpg",
    "/images/products/moroccan-hair-oil-100ml-7.jpg",
    "/images/products/moroccan-hair-oil-100ml-8.jpg",
  ],
  "M3035": [
    "/images/products/scalp-care-shampoo-550ml-1.jpg",
    "/images/products/scalp-care-shampoo-550ml-2.jpg",
    "/images/products/scalp-care-shampoo-550ml-3.jpg",
    "/images/products/scalp-care-shampoo-550ml-4.jpg",
    "/images/products/scalp-care-shampoo-550ml-5.jpg",
    "/images/products/scalp-care-shampoo-550ml-6.jpg",
    "/images/products/scalp-care-shampoo-550ml-7.jpg",
    "/images/products/scalp-care-shampoo-550ml-8.jpg",
  ],
  "M33": [
    "/images/products/joy-eau-de-parfum-30ml-1.jpg",
    "/images/products/joy-eau-de-parfum-30ml-2.jpg",
    "/images/products/joy-eau-de-parfum-30ml-3.jpg",
    "/images/products/joy-eau-de-parfum-30ml-4.jpg",
    "/images/products/joy-eau-de-parfum-30ml-5.jpg",
    "/images/products/joy-eau-de-parfum-30ml-6.jpg",
    "/images/products/joy-eau-de-parfum-30ml-7.jpg",
    "/images/products/joy-eau-de-parfum-30ml-8.jpg",
  ],
  "M366": [
    "/images/products/glow-cream-50ml-1.jpg",
    "/images/products/glow-cream-50ml-2.jpg",
    "/images/products/glow-cream-50ml-3.jpg",
    "/images/products/glow-cream-50ml-4.jpg",
    "/images/products/glow-cream-50ml-5.jpg",
    "/images/products/glow-cream-50ml-6.jpg",
    "/images/products/glow-cream-50ml-7.jpg",
    "/images/products/glow-cream-50ml-8.jpg",
  ],
  "M5160": [
    "/images/products/rose-body-wash-500ml-1.jpg",
    "/images/products/rose-body-wash-500ml-2.jpg",
    "/images/products/rose-body-wash-500ml-3.jpg",
    "/images/products/rose-body-wash-500ml-4.jpg",
    "/images/products/rose-body-wash-500ml-5.jpg",
    "/images/products/rose-body-wash-500ml-6.jpg",
    "/images/products/rose-body-wash-500ml-7.jpg",
    "/images/products/rose-body-wash-500ml-8.jpg",
  ],
  "M68": [
    "/images/products/ember-eau-de-parfum-30ml-1.jpg",
    "/images/products/ember-eau-de-parfum-30ml-2.jpg",
    "/images/products/ember-eau-de-parfum-30ml-3.jpg",
    "/images/products/ember-eau-de-parfum-30ml-4.jpg",
    "/images/products/ember-eau-de-parfum-30ml-5.jpg",
    "/images/products/ember-eau-de-parfum-30ml-6.jpg",
    "/images/products/ember-eau-de-parfum-30ml-7.jpg",
    "/images/products/ember-eau-de-parfum-30ml-8.jpg",
  ],
  "M8001": [
    "/images/products/radiance-essence-60ml-1.jpg",
    "/images/products/radiance-essence-60ml-2.jpg",
    "/images/products/radiance-essence-60ml-3.jpg",
    "/images/products/radiance-essence-60ml-4.jpg",
    "/images/products/radiance-essence-60ml-5.jpg",
    "/images/products/radiance-essence-60ml-6.jpg",
    "/images/products/radiance-essence-60ml-7.jpg",
    "/images/products/radiance-essence-60ml-8.jpg",
  ],
  "M8002": [
    "/images/products/revival-essence-mist-100ml-1.jpg",
    "/images/products/revival-essence-mist-100ml-2.jpg",
    "/images/products/revival-essence-mist-100ml-3.jpg",
    "/images/products/revival-essence-mist-100ml-4.jpg",
    "/images/products/revival-essence-mist-100ml-5.jpg",
    "/images/products/revival-essence-mist-100ml-6.jpg",
    "/images/products/revival-essence-mist-100ml-7.jpg",
    "/images/products/revival-essence-mist-100ml-8.jpg",
  ],
  "M8003": [
    "/images/products/night-recovery-cream-50g-1.jpg",
    "/images/products/night-recovery-cream-50g-2.jpg",
    "/images/products/night-recovery-cream-50g-3.jpg",
    "/images/products/night-recovery-cream-50g-4.jpg",
    "/images/products/night-recovery-cream-50g-5.jpg",
    "/images/products/night-recovery-cream-50g-6.jpg",
    "/images/products/night-recovery-cream-50g-7.jpg",
    "/images/products/night-recovery-cream-50g-8.jpg",
  ],
  "M8013": [
    "/images/products/deep-cleansing-liquid-250ml-1.jpg",
    "/images/products/deep-cleansing-liquid-250ml-2.jpg",
    "/images/products/deep-cleansing-liquid-250ml-3.jpg",
    "/images/products/deep-cleansing-liquid-250ml-4.jpg",
    "/images/products/deep-cleansing-liquid-250ml-5.jpg",
    "/images/products/deep-cleansing-liquid-250ml-6.jpg",
    "/images/products/deep-cleansing-liquid-250ml-7.jpg",
    "/images/products/deep-cleansing-liquid-250ml-8.jpg",
  ],
  "M8016": [
    "/images/products/pdrn-hyaluronic-serum-200ml-1.jpg",
    "/images/products/pdrn-hyaluronic-serum-200ml-2.jpg",
    "/images/products/pdrn-hyaluronic-serum-200ml-3.jpg",
    "/images/products/pdrn-hyaluronic-serum-200ml-4.jpg",
    "/images/products/pdrn-hyaluronic-serum-200ml-5.jpg",
    "/images/products/pdrn-hyaluronic-serum-200ml-6.jpg",
    "/images/products/pdrn-hyaluronic-serum-200ml-7.jpg",
    "/images/products/pdrn-hyaluronic-serum-200ml-8.jpg",
  ],
  "M8023": [
    "/images/products/b5-b12-cleansing-water-200ml-1.jpg",
    "/images/products/b5-b12-cleansing-water-200ml-2.jpg",
    "/images/products/b5-b12-cleansing-water-200ml-3.jpg",
    "/images/products/b5-b12-cleansing-water-200ml-4.jpg",
    "/images/products/b5-b12-cleansing-water-200ml-5.jpg",
    "/images/products/b5-b12-cleansing-water-200ml-6.jpg",
    "/images/products/b5-b12-cleansing-water-200ml-7.jpg",
    "/images/products/b5-b12-cleansing-water-200ml-8.jpg",
  ],
};
